### ISSUE TITLE
Classic Theme Icons Not Displaying

### ISSUE THREAD

**Issue by fcpchristopher** [zendesklabs/themes#17]
When previewing the theme (imported via forked GitHub), the Classic Theme doesn't seem to load the icons except the Community Icon.
I inspected the elements and the Community icon has an img src, where the others just have "img class=icon" and no "img src" specified (comparative example is the How-Tos).

![img_Diff](https://user-images.githubusercontent.com/19610309/62552846-ebc65f80-b833-11e9-827b-6fa6a245be75.png)

**Comment by fcpchristopher** [comment]
![ClassicIcons](https://user-images.githubusercontent.com/19610309/62552878-f8e34e80-b833-11e9-843b-6455e62320bd.png)

**Comment by ts-1** [comment]
@fcpchristopher you need to update the category id in script.js file in order to add icons for your category.

Take a look at script.js file and you will find the list of category ids there. Replace them with your's and you will be able to see the icon for your categories on homepage.
