### ISSUE TITLE
Doc_theme displays categories/sections in the left sidebar that should invisible to certain user segments

### ISSUE THREAD

**Issue by brettandersonddw** [zendesklabs/themes#19]
Suppose there is a category with no articles that are visible to anonymous or end users (such as Drafts)

Within the main body of the page, this category does not show (which is to be expected)

It does show on the left sidebar, however

![image](https://user-images.githubusercontent.com/51755588/66075818-0100f700-e522-11e9-9282-0cd3da3c4872.png)

**Comment by katisanse** [comment]
I encountered the same issue with this template and found that it only happens when _previewing_ the template as anonymous/End User. When we made this live the category did not appear.
