### ISSUE TITLE
Unable to import from github

### ISSUE THREAD

**Issue by bkarv** [zendesklabs/themes#21]
First of thanks for themes, the doc theme is exactly what I have been looking for. The only issue I am having trouble importing. When I try to add the git url 
https://github.com/zendesklabs/themes/
I get the error:
`We were unable to find this file: manifest.json.`

If i try adding the doc_them url 
https://github.com/zendesklabs/themes/tree/master/doc_theme

I get the error:
`The provided repository path is not a recognised pattern`

How do I import the doc theme into zendesk?

**Comment by roshans124** [comment]
Here, follow these steps:
1. Download the repo. It'll download all themes into a zip file named themes-master.zip
2. Unzip themes-master.zip
3. Find the theme that you want. Eg. "classic_theme" inside the unzipped folder
4. Zip this folder of the theme you want
5. Import it into Zendesk.
