### ISSUE TITLE
Doc Theme - Subsections in Sidebar

### ISSUE THREAD

**Issue by Toolbox1920** [zendesklabs/themes#23]
I'm working on the Doc Theme for my ZD Guide instance and noticed it didn't have the code for displaying subsections. I added the code from ZD's recipe page to enable them in the normal section page, but I wanted to see if it's possible to add subsections to the side bar as well.

**Comment by skipjac** [comment]
That is a newer feature we haven't added to this. We are going to move these themes to a different group which will support them going forward.
