### ISSUE TITLE
Footer is not shown

### ISSUE THREAD

**Issue by andrew-noh** [zendesklabs/themes#24]
Footer is not being displayed in Doc theme. (Have tested only Doc theme)
Users cannot select language.

Please let me know if there is a way to show footer.

![home](https://user-images.githubusercontent.com/26237146/75087148-184b8a00-5580-11ea-801f-055559907f4f.png)

**Comment by sdavos** [comment]
Try to remove this style balise
![image](https://user-images.githubusercontent.com/38280946/75668620-dc987a80-5c79-11ea-8fcb-bdc19cd7e343.png)
