### ISSUE TITLE
Nest theme will not import

### ISSUE THREAD

**Issue by stevehweb** [zendesklabs/themes#6]
Theme importer declares trouble importing the nest theme:

"We were unable to find this file" templates/article_page.hbs."

It seems that the article, category and contributions pages are named incorrectly?

**Comment by Sneakyway** [comment]
Hi I'm facing the same issue, will this issue be fixed in the near future?

**Comment by jacvoyt** [comment]
Same thing is happening for me.  Can anyone help to fix the import issue?

**Comment by moderatorwes** [comment]
The issue has been resolved thanks to @ts-1 

https://github.com/zendesklabs/themes/pull/7
